site_name: Onegini Flutter Plugin
nav:
  - Home: 'index.md'
  - '1. Topic Guides':
    - '1.1. Getting started': 'topic-guides/1-getting-started.md'
    - '1.2. Configuration': 'topic-guides/2-configuration.md'
    - '1.3. User registration': 'topic-guides/3-user-registration.md'
  - '2. Reference Guides':
    - '2.1. start app': 'reference-guides/2-start.md'
    - '2.2. user': 'reference-guides/2.2-user.md'
    - '2.2.1. AuthenticationHandler': 'reference-guides/2.2.1-authenticationHandler.md'
