site_name: Onegini Flutter Plugin
nav:
  - Home: 'index.md'
  - '1. Topic Guides':
    - '1.1. Getting started': 'topic-guides/1-getting-started.md'
    - '1.2. Configuration': 'topic-guides/2-configuration.md'
    - '1.3. User registration': 'topic-guides/3-user-registration.md'
    - '1.4. User authentication': 'topic-guides/4-user-authentication.md'
    - '1.5. User authentication with system biometric authenticators': 'topic-guides/5-user-authentication-with-biometric.md'
    - '1.6. Change pin': 'topic-guides/6-change-pin.md'
  - '2. Reference Guides':
    - '2.1. start app': 'reference-guides/start.md'
    - '2.2. user': 'reference-guides/user.md'
    - '2.2.1. RegisterUser': 'reference-guides/registerUser.md'
    - '2.2.2. DeregisterUser': 'reference-guides/deregisterUser.md'
    - '2.2.3. GetIdentityProviders': 'reference-guides/getIdentityProviders.md'
    - '2.2.4. AuthenticateUser': 'reference-guides/authenticateUser.md'
    - '2.2.5. RegisterAuthenticators': 'reference-guides/registerAuthenticators.md'
    - '2.2.6. GetRegisteredAuthenticators': 'reference-guides/getRegisteredAuthenticators.md'
    - '2.2.7. GetNotRegisteredAuthenticators': 'reference-guides/getNotRegisteredAuthenticators.md'
    - '2.2.8. FetchUserProfiles': 'reference-guides/fetchUserProfiles.md'
    - '2.2.9. Logout': 'reference-guides/logout.md'
    - '2.2.10. GetAppToWebSingleSignOn': 'reference-guides/getAppToWebSingleSignOn.md'
    - '2.2.11. MobileAuthWithOtp': 'reference-guides/mobileAuthWithOtp.md'
    - '2.2.12. ChangePin': 'reference-guides/changePin.md'
